name: Publish Package

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+*"
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Verify commit exists in origin/main
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/main
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      shell: bash
    - name: Build
      run: dotnet build --configuration Release /p:Version=${env:VERSION}
    - name: Test
      run: dotnet test --configuration Release /p:Version=${env:VERSION} --no-build
    - name: Pack
      run: dotnet pack projects\WinFormMarkup\WinFormMarkup.csproj --configuration release /p:Version=${env:VERSION} --no-build --output .
    - name: Push
      run: |
        dotnet nuget push .\WinFormMarkup.${env:VERSION}.nupkg --source https://nuget.pkg.github.com/bigtlb/index.json --api-key ${env:GITHUB_TOKEN}
        dotnet nuget push .\WinFormMarkup.${env:VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${env:NUGET_APIKEY}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
